config/routes.rb
Tester::Application.routes.draw do

  root to: "static_pages#home"

  get "/contact" => "contact#new"
  post "/contact" => "contact#create"

  resources :sessions, only: [:new, :create, :destroy] do
    collection do
      get 'password_reset'
      post 'request_reset'
    end
  end

  get '/signin' => "sessions#new"
  delete '/signout' => "sessions#destroy"

  resources :users do
    member do
      get 'change_password'
      patch 'update_password'
    end
  end
  get '/signup' => "users#new"

  resources :trees
  resources :nodes

  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                   :integer          not null, primary key
#  first_name           :string(255)
#  last_name            :string(255)
#  email                :string(255)
#  username             :string(255)
#  created_at           :datetime
#  updated_at           :datetime
#  password_digest      :string(255)
#  remember_token       :string(255)
#  password_reset_token :string(255)
#  password_reset_at    :datetime
#  is_admin             :boolean
#

class User < ActiveRecord::Base
	include SharedMethods
	
	has_secure_password

	before_save do
		username.downcase! unless username.nil?
		email.downcase! unless email.nil?
		is_admin = !!is_admin
		generate_token(:remember_token)
	end

	has_many :trees, foreign_key: "owner_id"

	def full_name
		first_name + " " + last_name
	end

	def prep_password_reset
		generate_token(:password_reset_token)
		self.password_reset_at = Time.zone.now
		save
		UserMailer.password_reset( self ).deliver
	end

	validates :first_name, presence: true, length: { maximum: 50 }
	validates :last_name, presence: true, length: { maximum: 50 }
	validates :username, presence: true, 
		length: { maximum: 50 }, uniqueness: { case_sensitive: false }

	validates :email, uniqueness: { case_sensitive: false }
	validate :email, :email_format

	validates_length_of :password, :minimum => 6, :maximum => 100, :allow_blank => true

	private

		def generate_token(column)
			begin
				self[column] = SecureRandom.urlsafe_base64
			end while User.exists?(column => self[column])
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	prepend_before_action :require_user,
		except: [:new, :create, :index]

	prepend_before_action :signed_in_user,
		except: [:new, :create, :change_password, :update_password ]

	prepend_before_action :unsigned_in_user,
		only: [ :new, :create ]

	before_action :is_current_user,
		only: [ :edit, :update ]

	before_action :allow_password_change,
		only: [ :change_password, :update_password ]

	before_action :is_admin,
		only: [ :index, :destroy ]

	def show
	end

	def index

	end
	
	def new
		@user = User.new
	end
	
	def create
		@user = User.new( user_params )
		if @user.save
			UserMailer.welcome( @user ).deliver
			sign_in @user
			redirect_to @user
		else
			render "new"
		end
	end
	
	def destroy

	end

	def edit
	end

	def update
		if @user.update_attributes( user_params )
			sign_in @user
			redirect_to @user
		else
			render "edit"
		end	
	end

	def change_password
		#@is_password_reset set before_action
	end

	def update_password
		#@is_password_reset set before_action
		can_change = true
		if !@is_password_reset &&
		   @user.authenticate( params[:old_password] ) != @user
			flash.now[:error] = "Existing password is incorrect"
			can_change = false
		elsif params[:new_password].blank?
			#Will overwrite past option
			flash.now[:error] = "New password may not be blank"
			can_change = false
		end

		@user.password = params[:new_password]
		@user.password_confirmation = params[:repeat_new_password]
			
		if !@user.valid?
			can_change = false
		end

		if can_change
			@user.save
			flash[:notice] = "Password Changed!"
			if @is_password_reset
				redirect_to root_path
			else
				sign_in @user
				render 'show'
			end
		else
			render 'change_password'
		end
	end

	private

		def user_params
			params.require(:user).permit(:first_name, :last_name, :email, :username,
										 :password, :password_confirmation )
		end	

		def require_user
			@user = User.find( params[:id] )
		end

		def is_current_user
			auth_redirect unless @user == current_user
		end

		def allow_password_change
			@token = params[:token]
			@is_password_reset = !@token.nil?

			return if @user == current_user
			
			if @user.password_reset_token.nil? || @user.password_reset_at.nil?
				auth_redirect
			elsif @user.password_reset_token != @token
				auth_redirect
			elsif @user.password_reset_at < 2.hours.ago
				flash[:notice] = "Password reset has expired."
				redirect_to password_reset_sessions_path
			end
			#proceed
		end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: @user %>

<div class="row">
	<div class="span4">
		<%= f.label :username %>
		<%= f.text_field :username, class:"span4" %>
	</div>
	<div class="span4">
		<%= f.label :email %>
		<%= f.text_field :email, class:"span4" %>
	</div>
</div>

<div class="row">
	<div class="span4">
		<%= tooltip_label f.label(:first_name), "By default, only your username is visable on this site." %>
		<%= f.text_field :first_name, class:"span4" %>
	</div>
	<div class="span4">
		<%= f.label :last_name %>
		<%= f.text_field :last_name, class:"span4" %>
	</div>
</div>

<div class="row">
	<div class="span4">
		<%= f.label :password %>
		<%= f.password_field :password, class:"span4" %>
	</div>
	<div class="span4">
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation, class:"span4" %>
	</div>
</div>

app/views/users/change_password.html.erb
<% provide( :title, 'Change Password' ) %>

<section>
	<h1>Change Password</h1>

	<%= form_tag update_password_user_path(@user), method: 'patch' do %>

		<%= render( 'shared/error_messages', object: @user ) unless @user.nil? %>

		<% if @is_password_reset %>
			<%= hidden_field_tag :token, @token %>
		<% else %>
			<%= label_tag :old_password %>
			<%= password_field_tag :old_password %>
			<br>
		<% end %>

		<%= label_tag :new_password %>
		<%= password_field_tag :new_password %>
		<br>

		<%= label_tag :repeat_new_password %>
		<%= password_field_tag :repeat_new_password %>
		<br>
		<%= submit_tag "Change Password" %>
		
	<% end %>
</section>

app/views/users/edit.html.erb
<% provide( :title, 'Edit Profile' ) %>

<section>
	<h1>Sign Up</h1>

	<%= form_for( @user ) do |f| %>
		<%= link_to "Change Password", change_password_user_path(@user) %>
		<br>
		<%= render 'users/fields', f: f %>

		<%= f.submit "Submit Changes" %>
		
	<% end %>
</section>

app/views/users/index.html.erb
<% provide( :title, 'All Users' ) %>

<section>
	<h1>All Users</h1>

	<% User.all.each do |user| %>
		<%= link_to user.username, user %>
	<% end %>
</section>

app/views/users/new.html.erb
<% provide( :title, 'Sign up' ) %>

<section>
	<h1>Sign Up</h1>

	<%= form_for @user, html: { class:"span8 ctr" } do |f| %>
		<%= render 'users/fields', f: f %>
		<br>
		<%= f.submit "Create Account", class:"btn btn-primary btn-large ctr" %>
		
	<% end %>
</section>

app/views/users/show.html.erb
<% provide( :title, 'User Profile' ) %>

<section>

	<h1><%= current_user?(@user) ? "Your Profile" : "User Profile" %></h1>
	<div class="row-fluid">

		<section class="span8 text-center">
			<%= render 'shared/recent_trees', trees: @user.trees, n: 4 %>
			<%= link_to "Create a new Tree", new_tree_path, class:"btn btn-primary" %>
		</section>


		<section class="span4 well" id="infoBox">
			<h2>
				Account Info
				<%= link_to "edit", edit_user_path( @user ), class:"editLink" %>
			</h2>
			<table class="table">
				<tr>
					<td>Username</td>
					<td><%= @user.username %></td>
				</tr>
				<tr>
					<td>Name</td>
					<td><%= @user.full_name %></td>
				</tr>
				<tr>
					<td>Account Created</td>
					<td><%= as_date( @user.created_at ) %></td>
				</tr>
			</table>
		</section>

	</div>
	
</section>