config/routes.rb
Tester::Application.routes.draw do

  root to: "static_pages#home"

  get "/contact" => "contact#new"
  post "/contact" => "contact#create"

  resources :sessions, only: [:new, :create, :destroy] do
    collection do
      get 'password_reset'
      post 'request_reset'
    end
  end

  get '/signin' => "sessions#new"
  delete '/signout' => "sessions#destroy"

  resources :users do
    member do
      get 'change_password'
      patch 'update_password'
    end
  end
  get '/signup' => "users#new"

  resources :trees
  resources :nodes

  

end

app/models/tree.rb
# == Schema Information
#
# Table name: trees
#
#  id         :integer          not null, primary key
#  owner_id   :integer
#  title      :string(255)
#  created_at :datetime
#  updated_at :datetime
#  root_id    :integer
#

class Tree < ActiveRecord::Base

	belongs_to :owner, class_name: "User"
	belongs_to :root, class_name: "Node", dependent: :destroy

	validates :title, presence: true, length: { maximum: 250 }
	validates :owner_id, presence: true

	before_save do
		self.root = Node.create! if root.nil?
	end

	def nodes
		def gather( node )
			node.children.collect{ |c| gather c } << node
		end
		gather( root ).flatten
	end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController

    prepend_before_action :require_tree,
        except: [:new, :create, :index]

    prepend_before_action :signed_in_user,
        only: [:new, :create ]

    before_action :is_current_owner,
        only: [ :edit, :update ]

    before_action :is_admin,
        only: [ :destroy ]

    def new
        @tree = Tree.new
    end

    def create
        @tree = current_user.trees.build( tree_params )
        if @tree.save
            redirect_to @tree
        else
            render :new
        end

    end

    def edit
        gon.runEditBranch = true
        gon.nodes         = @tree.nodes.index_by(&:id)
        gon.rootId        = @tree.root.id
        gon.updatePath    = nodes_path
    end

    def update
    end

    def show
    end

    def index
    end

    def destroy
    end

    private

        def tree_params
            params.require(:tree).permit(:title)
        end 

        def require_tree
            @tree = Tree.find( params[:id] )
        end

        def is_current_owner
            auth_redirect unless current_user?( @tree.owner )
        end


end

app/helpers/trees_helper.rb
module TreesHelper
=begin
	def build_branches( tree )
		str = "<ul id='branchEditList'>"
		tree.root.children.each do |node|
			build_branches_r( node, str )
		end
		str << "<li>"
		str << render( "add_branch", parent: tree.root )
		str << "</li>"
		str << "</ul>"
		return str.html_safe
	end

	def build_branches_r( node, str )
		str << "<li>"
		str << "<span class='node' id='node#{node.id}'>"
		str << ( node.text.strip.empty? ? "Click to edit" : node.text )
		str << "</span>"
		if node.children.any?
			str << "<ul>"
			node.children.each do |c|
				build_branches_r( c, str )
			end
			str << "</ul>"
		end
		str << "</li>"
	end
=end

end

app/views/trees/_add_branch.html.erb
<%= form_for( Node.new, remote: true) do |f| %>
  <%= hidden_field_tag :parent_id, parent.id %>
  <%= f.submit "New Branch", class: "btn btn-link" %>
<% end %>

app/views/trees/edit.html.erb
<% provide( :title, @tree.title ) %>

<section>
	<h1><%= @tree.title %></h1>

	<div class="row-fluid">

		<section class="span7">
		</section>

		<section class="span5 well" id="infoBox">
			<h2>Branches</h2>
			<ul id="branchEditList"></ul>
		</section>

	</div>

</section>

app/views/trees/index.html.erb
<h1>Trees#index</h1>
<p>Find me in app/views/trees/index.html.erb</p>

app/views/trees/new.html.erb
<% provide( :title, 'New Tree' ) %>

<section>
	<h1>New Tree</h1>

	<%= form_for @tree do |f| %>
		<%= render 'shared/error_messages', object: @tree %>
		<%= f.label :title %>
		<%= f.text_field :title, class:"span4" %>
		<%= f.submit "Create Tree", class:"btn btn-primary btn-large ctr" %>		
	<% end %>
</section>

app/views/trees/show.html.erb
<% provide( :title, @tree.title ) %>

<section>
	<h1><%= @tree.title %></h1>

	<p class="text-center">
		<% if current_user?( @tree.owner ) %>
			<%= link_to "Edit", edit_tree_path( @tree ), id:"editTree", class:"btn btn-success" %>
		<% end %>
	</p>

	<div class="row-fluid">

		<section class="span7">
		</section>

		<section class="span5 well" id="infoBox">
			<h2>Branches</h2>
		</section>

	</div>

</section>