config/routes.rb
Tester::Application.routes.draw do

  root to: "static_pages#home"

  get "/contact" => "contact#new"
  post "/contact" => "contact#create"

  resources :sessions, only: [:new, :create, :destroy] do
    collection do
      get 'password_reset'
      post 'request_reset'
    end
  end

  get '/signin' => "sessions#new"
  delete '/signout' => "sessions#destroy"

  resources :users do
    member do
      get 'change_password'
      patch 'update_password'
    end
  end
  get '/signup' => "users#new"

  resources :trees
  resources :nodes

  

end

app/views/layouts/_head.html.erb
<head>
  	<title><%= full_title yield(:title) %></title>

  	<%= include_gon %>
	<%= render "layouts/jquery" %>

	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>

</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<%= link_to "Entrepreserve", root_path, class: "brand" %>
  			<div class="nav-collapse collapse">
				<nav>
					<ul class="nav pull-right">
						<%= render 'layouts/nav_links' %>
					</ul>
				</nav>
			</div>
		</div>
	</div>
</header>

app/views/layouts/_jquery.html.erb
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_login.html.erb
<%= form_tag sessions_path, id:"loginArea" do %>

	<%= text_field_tag :email, '', placeholder: "email" %>
	<%= password_field_tag :password, '', placeholder: "password" %>

	<%= link_to "Sign up", signup_path %>
	<%= submit_tag 'Log In', id: "signin", class: "btn btn-primary" %>
	<%= link_to "Forgot?", password_reset_sessions_path, id: "forgot" %>
<% end %>

app/views/layouts/_nav_links.html.erb
<li><%= link_to "Home", root_path %></li>

<li class="dropdown">
	<%= dropdown_link "About" %>

	<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
 		<li><%= link_to "Our Mission", "#" %></li>
		<li><%= link_to "About Us", "#" %></li>
		<li><%= link_to "FAQ", "#" %></li>
	</ul>
</li>

<li class="dropdown">
	<%= dropdown_link "Products" %>

	<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
 		<li><%= link_to "Downloads", "#" %></li>
		<li><%= link_to "Kits", "#" %></li>
	</ul>
</li>

<li><%= link_to "Contact", contact_path %></li>

<% if signed_in? %>

	<li class="dropdown">
		<%= dropdown_link current_user.username %>

		<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
 			<li><%= link_to "Profile", user_path( current_user ) %></li>
			<li><%= link_to "Edit Profile", edit_user_path( current_user ) %></li>
			<li class="divider"></li>
			<li><%= link_to "Sign Out", signout_path, method: "delete", id: "signout"  %></li>
		</ul>
	</li>

<% else %>
	<li class="dropdown">
		<%= dropdown_link "Sign In" %>
		<div class="dropdown-menu" >
			<%= render 'layouts/login' %>
		</div>
	</li>
<% end %>

app/views/layouts/_notifications.html.erb
<section id="notifications" class="span6 ctr">

	<% alerts = [] %>
	<% if flash[:notice] %>
		<% alerts.push( flash[:notice] ) %>
	<% end %>
	<% if flash[:alert] %>
		<% alerts.push( flash[:alert] ) %>
	<% end %>

	<% errors = [] %>
	<% if flash[:error] %>
		<% errors << flash[:error] %>
	<% end %>
	<% yield(:form_errors) %>
	<% unless @form_errors.nil? %>
		<% errors = ( errors << @form_errors ).flatten %>
	<% end %>

	<div id="javascriptWarning" class="alert">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<p>This site functions best with javascript enabled!</p>
	</div>

	<% unless alerts.empty? %>
		<div id="alerts"class="alert alert-info alert-block">
			<button type="button" class="close" data-dismiss="alert">&times;</button>

			<% alerts.each do |alert| %>
				<p><%= alert %></p>
			<% end %>
		</div>
	<% end %>

	<% unless errors.empty? %>
		<div id="errors" class="alert alert-error alert-block">
			<button type="button" class="close" data-dismiss="alert">&times;</button>

			<ul>
				<% errors.each do |error| %>
					<li><%= error %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<%= render "layouts/head" %>

<body>
	<%= render "layouts/header" %>
	<div class="container">
		<%= render "layouts/notifications" %>
		<%= yield %>
	</div>
</body>

</html>